feat(server/http): add server
go-orb/plugins pull request #3
Opened 2022-11-02 19:10 UTC by Davincible

2022-11-02 19:10 UTC, Davincible commented
We need to add the logger here

2022-11-14 00:05 UTC, jochumdev requested changes

2022-11-14 00:05 UTC, jochumdev commented on server/http/router/router/pluings.go
> +package router
Typo in filename

2022-11-14 00:05 UTC, jochumdev commented on server/http/router/router/router.go
> +// Some methods were removded as they were considered unnecessary for go-micro.
removed

2022-11-14 00:05 UTC, jochumdev commented on server/http/utils/ip/ip.go
> +// Package ip provides validation and parsing utilities.
How does this work with ipv6 ? Seems not?

2022-11-14 00:05 UTC, jochumdev commented on server/http/utils/tls/tls.go
> +func GenTlSConfig(addr ...string) (*tls.Config, error) {
Shouldn't it be GenTLSConfig?

2022-11-14 00:05 UTC, jochumdev commented on server/http/utils/wg/wg.go
> +// Package wg implements a double waitgroup that can be used to keep track
This is very "clever" can you explain more what this is for?

2022-11-14 00:05 UTC, jochumdev commented on server/http/utils/wg/wg.go
> +// the waitgroup will impact both the global and local waiggroups, but waiting
Typo waitgroups

2022-11-14 00:05 UTC, jochumdev commented on server/tests/proto/generate.go
> +//go:generate wget -q -O google/api/annotations.proto https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/annotations.proto
May switch from wget to curl? wget is not every installed while curl mostly is.

2022-11-14 01:59 UTC, Davincible commented on server/http/utils/wg/wg.go
> +// Package wg implements a double waitgroup that can be used to keep track
Not my idea. It's already a v4 util. I really like it as well. I'm not sure if its at place here in the HTTP package, but should be used somewhere.

It allows you to add to a runtime used globally, but only wait for your added routines, and not all other routines, while at the same time giving the safety that the global process knows about your routines.

2022-11-14 02:13 UTC, Davincible commented on server/tests/proto/generate.go
> +//go:generate wget -q -O google/api/annotations.proto https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/annotations.proto
We could but it's not important, actually only needs to be done once, which it has been, just put it there for documentation

2022-11-14 04:47 UTC, jochumdev commented on server/http/utils/wg/wg.go
> +// Package wg implements a double waitgroup that can be used to keep track
So if it's not used you can delete it, right?

2022-11-14 23:48 UTC, Davincible commented on server/http/utils/ip/ip.go
> +// Package ip provides validation and parsing utilities.
Added tests

2022-11-15 06:02 UTC, merged